version: "3.9"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-linkedin_sim}
  app:
    image: ${IMAGE_NAME:-linkedin-clone-backend:latest}
    command: uvicorn services.recruiter_company_service.app.main:app --host 0.0.0.0 --port 8003
    env_file:
      - .env.aws
    depends_on:
      - mysql
    ports:
      - "8003:8003"
