version: "3.9"
services:
  mongo:
    image: mongo:7
  redis:
    image: redis:7
  app:
    image: ${IMAGE_NAME:-linkedin-clone-backend:latest}
    command: uvicorn services.messaging_connections_service.app.main:app --host 0.0.0.0 --port 8006
    env_file:
      - .env.aws
    depends_on:
      - mongo
      - redis
    ports:
      - "8006:8006"
